base/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from blog.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',home, name='home'),
    path('blog/', include('blog.urls')),
    path('users/',include('users.urls')),
    path('accounts/', include('allauth.urls')),
    path("ckeditor5/", include('django_ckeditor_5.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('create/', views.create, name='create'),
    path('blogs/', views.blogs, name='blogs'),
    path('<slug:slug>/', views.detail, name='detail'),
    path('update/<int:pk>/', views.update, name='update'),
    path('delete/<int:pk>/', views.delete_post, name='delete'),
    path('tags/<slug:tag>/', views.home, name='posts_by_tag'),

]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'
urlpatterns = [
    path('update-profile/', views.update_profile, name='update_profile'),
    path('profile/', views.profile, name='profile'),
]

blog/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse 
from django.contrib.auth import get_user_model
from taggit.managers import TaggableManager
from pilkit.processors import ResizeToFill
from imagekit.models import ImageSpecField
from django_ckeditor_5.fields import CKEditor5Field


# Create your models here.

User = get_user_model()


class Post(models.Model):
    title= models.CharField(max_length=250)
    image = models.ImageField(upload_to="blog/")
    body = CKEditor5Field('Text', config_name='extends')
    slug = models.SlugField(blank=True, default="", max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(User,on_delete=models.CASCADE)
    image_thumbnail = ImageSpecField(source='image', processors=[ResizeToFill(1200,300)], format='JPEG',options={'quality':60})
    tags = TaggableManager()

    
    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)
    
    def get_absolute_url(self):
        return reverse('blog:detail', args=[str(self.slug)])
    
    
    def __str__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from pilkit.processors import ResizeToFill
from imagekit.models import ImageSpecField

# Create your models here.

GENDER = (('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'),)


class CustomUser(AbstractUser):
    photo = models.ImageField(upload_to='profiles/', default='profiles/default.png')
    phone_number = models.CharField(max_length=15, null=True, blank=True)
    gender = models.CharField(
        max_length=200, choices=GENDER, null=True, blank=True)
    image_thumbnail = ImageSpecField(source='photo', processors=[ResizeToFill(150,150)], format='JPEG',options={'quality':60})

    
    def __str__(self):
        return self.email

blog/forms.py
from .models import Post
from django.forms import ModelForm
from django_ckeditor_5.widgets import CKEditor5Widget
from django import forms



class PostForm(ModelForm):
    body = forms.CharField(widget=CKEditor5Widget())
    class Meta:
        model = Post
        fields = ['title','image','body','tags','slug']

class PostDeleteForm(ModelForm):
    class Meta:
        model = Post
        fields = []

users/forms.py
from allauth.account.forms import SignupForm
from .models import CustomUser
from django import forms


GENDER = (('Female', 'Female'), ('Male', 'Male'), ('Other', 'Other'),)

class CustomSignupForm(SignupForm):
    phone_number = forms.CharField(max_length=12, label='Phone Number', required=False)
    gender = forms.MultipleChoiceField(choices=GENDER, required=False)
    photo  = forms.ImageField( required=False)
    
    def save(self, request):
        user = super(CustomSignupForm, self).save(request)
        user.phone_number = self.cleaned_data['phone_number']
        user.gender = self.cleaned_data['gender']
        user.photo = self.cleaned_data['photo']
        user.save()
        return user

class UpdateProfileForm(forms.ModelForm):
    model = CustomUser
    fields = ['phone_number', 'gender', 'photo','username']
    
    def __init__(self, *args, **kwargs):
        super(UpdateProfileForm, self).__init__(*args, **kwargs)
        # Optionally customize your form fields here, for example:
        self.fields['gender'].widget.attrs.update({'class': 'form-control'})
        self.fields['phone_number'].widget.attrs.update({'class': 'form-control'})
        self.fields['photo'].widget.attrs.update({'class': 'form-control-file'})
        self.fields['username'].widget.attrs.update({'class':'form-control'})

blog/views.py
from django.shortcuts import render,get_object_or_404, redirect
from .models import Post
from .forms import PostForm,PostDeleteForm
from django.contrib.auth.decorators import login_required
from taggit.models import Tag
from django.core.paginator import Paginator


# Create your views here.
def home(request):
    posts = Post.objects.all()
    
    context = {
        'posts':posts
    }
    return render(request, 'pages/home.html', context)

def blogs(request, tag=None):
    tag_obj = None
    
    if not tag:
        posts = Post.objects.all()
    else:
        tag_obj = get_object_or_404(Tag, slug=tag)
        posts = Post.objects.filter(tags__in=[tag_obj])
    
    paginator = Paginator(posts, 6)
    page = request.GET.get('page')
    posts = paginator.get_page(page)
    
    context = {
        'posts':posts,
        'tag':tag_obj
    }
    return render(request, 'blog/blogs.html', context)

def detail(request, slug=None):
    post = get_object_or_404(Post,slug=slug)
    context = {
        'post':post
    }
    return render(request, 'blog/detail.html', context)

@login_required(login_url='account_login')
def create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('home')
    else:
        form = PostForm()
        context = {
            'form':form
        }
    return render(request, 'blog/create.html',context)

@login_required(login_url='account_login')
def update(request,pk):
    post = get_object_or_404(Post, pk=pk)
    
    if request.method == 'POST':
        form = PostForm(request.POST,request.FILES, instance=post)
        if form.is_valid():
            form.save()
            return redirect('blog:detail', slug=post.slug)
    else:
        form = PostForm(instance=post)
        context = {
            'form':form,
            'post':post
        }
    return render(request, 'blog/update.html', context)

@login_required(login_url='account_login')
def delete_post(request, pk):
    post = get_object_or_404(Post, pk=pk)
    
    if request.method == 'POST':
        form = PostDeleteForm(request.POST,instance=post)
        if form.is_valid():
            post.delete()
            return redirect('home')
    else:
        form = PostDeleteForm(instance=post)
        context = {
            'post':post,
            'form':form
        }
        return render(request, 'blog/delete.html',context)

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import UpdateProfileForm
from django.contrib.auth import get_user_model

# Create your views here.
User = get_user_model()

@login_required(login_url='account_login')
def update_profile(request):
    user = request.user
    if request.method == 'POST':
        form = UpdateProfileForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = UpdateProfileForm(instance = user)
    context = {
        'form':form
    }
    return render(request,'users/update.html',context)

@login_required(login_url='account_login')
def profile(request):
    user = request.user
    profile = get_object_or_404(User, user=user)
    
    context ={
        profile:profile
    }
    
    return render(request, 'users/profile.html', context)

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Blog App</title>
    <link href="{% static 'css/output.css' %}" rel="stylesheet" />
  </head>
  <body>
    {% include 'partials/navigation.html' %}
    <main class="mt-5">{% block content %} {% endblock %}</main>
  </body>
  {% block javascript %} {% endblock %}
  <script src="{% static 'js/app.js' %}"></script>
</html>

templates/blog/blogs.html
{% extends "base.html" %} {% block content %} {% if tag %}
<p>Posts tagged with <strong>"{{ tag.name }}"</strong></p>

{% endif %} {% for post in posts %}
<a href="{{post.get_absolute_url}}">{{ post.pk }} : {{ post }}</a>
<h1>{{post.title}}</h1>
<p>{{post.body|safe}}</p>
<img src="{post.image.url}" alt="" />

<section>
  {% if posts.has_previous %}
  <a href="?page=1">1</a>
  <a href="?page={{ posts.previous_page_number }}"
    >{{posts.previous_page_number}}</a
  >
  {% endif %}
  <span>{{ posts.number }}</span>
  <span>of</span>
  <span>{{ posts.paginator.num_pages }}</span>
  {% if post.has_next %}
  <a href="?page={{ posts.next_page_number }}">Next</a>
  <a href="?page={{ posts.paginator.num_pages }}"
    >{{ posts.paginator.num_pages }}</a
  >
  {% endif %}
</section>
{% endfor %} {% endblock %}

templates/blog/create.html
{% extends "base.html" %} {% block content %}
<section class="mt-16">
  <form method="POST" novalidate enctype="multipart/form-data" class="prose">
    {% csrf_token %} {{form.media}} {{form.as_p}}
    <button class="button" type="submit">Create</button>
  </form>
</section>
{% endblock %}

templates/blog/delete.html
{% extends "base.html" %} {% block content %}
<form action="{% url 'blog:delete' post.pk %}" method="post">
  {% csrf_token %} {{form}} Are you sure you want to delete this item:
  <a href="{% url 'blog:detail' post.slug %}">
    ({{ post.pk }}) {{ post.title }} </a
  >?

  <section>
    <button type="submit">Delete</button>
    <a href="{% url 'home' %}">Cancel</a>
  </section>
</form>
{% endblock %}

templates/blog/detail.html
{% extends "base.html" %} {% block content %}
<h1>Detail Page</h1>
<h1>{{post.title}}</h1>
<p>{{post.body}}</p>
<p>Posted {{ post.date|date:"M j, Y" }}</p>
<p>Updated {{ post.updated }}</p>
<p>{{post.author}}</p>
{% if post.tags %} {% for tag in post.tags.all %}
<a href="{% url 'blog:posts_by_tag' tag.slug %}">{{tag}}</a>
{% endfor %} {% endif %}
<a href="{% url 'blog:update' post.pk %}">update</a>
<a href="{% url 'blog:delete' post.pk %}">delete</a>
{% endblock %}

templates/blog/update.html
{% extends "base.html" %} {% block content %}
<section class="mt-16">
  <form method="POST" enctype="multipart/form-data" class="prose">
    {% csrf_token %} {{form.media}} {{form.as_p}}
    <button class="button" type="submit">update</button>
  </form>
</section>
{% endblock %}

templates/pages/home.html
{% extends "base.html" %} {% block content %} {% load static %}

<section class="text-gray-600 body-font">
  <div
    class="container mx-auto flex px-5 py-24 md:flex-row flex-col items-center">
    <div
      class="lg:flex-grow md:w-1/2 lg:pr-24 md:pr-16 flex flex-col md:items-start md:text-left mb-16 md:mb-0 items-center text-center">
      <h1
        class="title-font sm:text-4xl text-3xl mb-4 font-medium text-gray-900">
        Your Gateway to the <br class="hidden lg:inline-block" />Programming
        World
      </h1>
      <p class="mb-8 leading-relaxed">
        Stay ahead in the ever-evolving tech landscape. Our blog covers
        everything from front-end frameworks to back-end technologies, coding
        best practices, emerging languages, and deep dives into algorithms.
        Whether you're just starting out or looking to sharpen your skills,
        explore tutorials, tips, and insights on a wide variety of programming
        topics. Ready to level up your coding game?
      </p>
      <div class="flex justify-center">
        <button
          class="inline-flex text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded text-lg">
          Register
        </button>
        <button
          class="ml-4 inline-flex text-gray-700 bg-gray-100 border-0 py-2 px-6 focus:outline-none hover:bg-gray-200 rounded text-lg">
          Explore Blogs
        </button>
      </div>
    </div>
    <div class="lg:max-w-lg lg:w-full md:w-1/2 w-5/6 h-[400px]">
      <img
        class="object-cover object-center rounded h-full"
        alt="hero"
        src="{% static 'images/hero.png' %}" />
    </div>
  </div>
  <section>
    <h1>Latest Blogs</h1>
    {% for post in posts %}
    <a href="{{post.get_absolute_url}}">{{ post.pk }} : {{ post }}</a>
    <h1>{{post.title}}</h1>
    <div class="prose">{{ post.body|safe }}</div>

    {% endfor %}
  </section>
</section>

{% endblock %}

templates/partials/navigation.html
{% comment %}
<nav
  class="flex flex-wrap items-center justify-between p-3 text-gray-600 body-font w-full sticky">
  {% endcomment %}
  <nav
    class="fixed top-0 left-0 w-full z-50 bg-white shadow-md flex flex-wrap items-center justify-between p-3 text-gray-600 body-font">
    <a href="{% url 'home' %}">
      <svg
        xmlns="http://www.w3.org/2000/svg"
        width="30"
        height="30"
        fill="currentColor"
        class="bi bi-amd"
        viewBox="0 0 16 16">
        <path
          d="m.334 0 4.358 4.359h7.15v7.15l4.358 4.358V0zM.2 9.72l4.487-4.488v6.281h6.28L6.48 16H.2z" />
      </svg>
    </a>
    <div class="flex md:hidden">
      <button id="hamburger">
        <svg
          id="hamburger-icon"
          class="block"
          xmlns="http://www.w3.org/2000/svg"
          width="30"
          height="30"
          fill="currentColor"
          class="bi bi-list"
          viewBox="0 0 16 16">
          <path
            fill-rule="evenodd"
            d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5m0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5" />
        </svg>
        <svg
          id="close-icon"
          class="hidden"
          xmlns="http://www.w3.org/2000/svg"
          width="30"
          height="30"
          fill="currentColor"
          class="bi bi-x-lg"
          viewBox="0 0 16 16">
          <path
            d="M2.146 2.854a.5.5 0 1 1 .708-.708L8 7.293l5.146-5.147a.5.5 0 0 1 .708.708L8.707 8l5.147 5.146a.5.5 0 0 1-.708.708L8 8.707l-5.146 5.147a.5.5 0 0 1-.708-.708L7.293 8z" />
        </svg>
      </button>
    </div>
    <div
      id="nav-menu"
      class="toggle hidden w-full md:w-auto md:flex justify-center items-center text-bold mt-5 md:mt-0 gap-8 md:gap-6 p-10 md:p-0 flex-col md:flex-row shadow-2xl md:shadow-none">
      <a
        href="{% url 'home' %}"
        class="block text-center mb-5 md:mb-0 md:inline-block hover:text-gray-900"
        >Home</a
      >
      <a
        href="{% url 'blog:blogs' %}"
        class="block text-center mb-5 md:mb-0 md:inline-block hover:text-gray-900"
        >Blogs</a
      >
      <a
        href="{% url 'blog:create' %}"
        class="block text-center mb-5 md:mb-0 md:inline-block hover:text-gray-900"
        >New Article</a
      >
      <a
        href="{% url 'users:profile' %}"
        class="block text-center mb-5 md:mb-0 md:inline-block hover:text-gray-900"
        >Profile</a
      >
      {% if user.is_authenticated %}
      <a
        href="{% url 'account_logout' %}"
        class="block text-center md:inline-block px-4 py-2 bg-indigo-500 focus:outline-none hover:bg-indigo-600 text-white md:rounded">
        Logout
      </a>
      {% else %}
      <a
        href="{% url 'account_signup' %}"
        class="block text-center md:inline-block px-4 py-2 bg-indigo-500 focus:outline-none hover:bg-indigo-600 text-white md:rounded">
        Create Account
      </a>
      <a
        href="{% url 'account_login' %}"
        class="block text-center md:inline-block px-4 py-2 bg-indigo-500 focus:outline-none hover:bg-indigo-600 text-white md:rounded">
        Login
      </a>
      {% endif %}
    </div>
  </nav>
</nav>

templates/users/profile.html
{% extends "base.html" %} {% block content %} {{profile.username}}
{{profile.email}}
<img src="{{profile.photo.url}}" alt="" />
<a href="{% url 'account_change_password ' %}">Change Password</a>
{% endblock %}

templates/users/update.html
{% extends "base.html" %} {% block content %}
<h1>Update Your Profile</h1>
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %} {{ form|crispy }}
  <!-- If using crispy forms -->
  <button type="submit">Update Profile</button>
</form>
<a href="{% url 'profile' %}">Back to Profile</a>
<!-- Link back to the profile page -->

{% endblock %}